#################################################################
## Home Assistant
#################################################################

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml
  allowlist_external_dirs:
  - /config/camera_snapshot
  packages: !include_dir_named packages

frontend:
  themes: !include_dir_merge_named themes

webhook:
 
zigbee2mqtt_networkmap:
  #topic: your topic (optional, default zigbee2mqtt)
panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    url: '/local/community/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'  

#hacs:
 # token: !secret hacs
  #appdaemon: true
  
config:

system_health:

updater:
discovery:

energy:

conversation:
history:
logbook:
map:
sun:

recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 7

#lovelace:
 #mode: yaml

#################################################################
## Components
#################################################################


nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_secret
  project_id: !secret nest_projectid
  subscriber_id:  !secret nest_subscriberid

tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

google:
   client_id: !secret google_id
   client_secret: !secret google_secret

hue:
  bridges:
     - host: 192.168.86.46
     - host: 192.168.86.31
       allow_unreachable: true
       allow_hue_groups: false

ffmpeg:

stream:

mqtt:
 broker: 192.168.86.27
 discovery: true
 discovery_prefix: homeassistant
 username: !secret mqtt_username
 password: !secret mqtt_password
 birth_message:
   topic: 'hass/status'
   payload: 'online'
 will_message:
   topic: 'hass/status'
   payload: 'offline' 

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat

  - name: telegram_chris
    platform: telegram
    chat_id: !secret telegram_chris_chat

telegram_bot:
    platform: polling
    api_key: !secret telegram_api
    parse_mode: html
    allowed_chat_ids:
        - !secret telegram_chat
        - !secret telegram_chris_chat
        - !secret telegram_aimee_chat

 

influxdb:
  host: 192.168.86.9

#apcupsd:
 # host: 192.168.86.9

tplink:

weather:
#  - platform: metoffice
  #  api_key: !secret metoffice_api

#monkey_patch_nest_camera_event_end_date:

mobile_app:

proximity:
  home:
    ignored_zones:
      - work
    devices:
      - person.chris
      - person.aimee
    tolerance: 5
    unit_of_measurement: mi

webostv:
  host: 192.168.86.44
  name: Man Cave TV LG
  turn_on_action:
    service: persistent_notification.create
    data:
      message: "Turn on action"
  customize:
    sources:
      - livetv
      - youtube
      - makotv
      - netflix

#################################################################
## Includes
#################################################################

cloud: !include cloud.yaml
automation: !include_dir_merge_list automation
sensor: !include sensors.yaml
scene: !include scenes.yaml
group: !include groups.yaml
script: !include scripts.yaml
light: !include light_group.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
rest_command: !include rest_command.yaml
input_select: !include input_select.yaml
camera: !include cameras.yaml
timer: !include timers.yaml
switch: !include switch.yaml
device_tracker: !include device_tracker.yaml
#yeelight: !include yeelight.yaml
#googlehome: !include googlehome.yaml